name: Pub Publish Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Publishing Test (Dry Run)
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.8'
          channel: 'stable'
      - name: Documenting package
        run: |
          echo "FLUTTER_ROOT=$FLUTTER_HOME" >> $GITHUB_ENV
          bash scripts/credentials.sh
          make
          make deps
          flutter pub global activate dartdoc
          make docs
          flutter pub publish -n -v
